// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package otpservice

import (
	"otpServiceConsumer/otpRepository"
	"otpServiceConsumer/services/dbService"
)

// Injectors from wire.go:

func InitializeOTPService(phrase string) *OTPServiceImpl {
	mysqldbService := dbservice.NewDBServiceClientProvider(phrase)
	otpRepoImpl := otprepository.NewOTPRepoProvider(mysqldbService)
	otpServiceImpl := NewOTPServiceProvider(otpRepoImpl)
	return otpServiceImpl
}
